### ISSUE TITLE
Contributor guide

### ISSUE THREAD

**Issue by naorzr** [TylorS/typed-fp#5]
Hey @TylorS ,
I've read through the readme and so far liked what you're doing!

If you're open for contributions it would be great if you could add a contributor guide that describes conventions, how to contribute and possibly which stuff you'd like for people to help with.

**Comment by TylorS** [comment]
Hey @naorzr, I'm definitely open to contributions!

I haven't spent too much time thinking about this sort of thing, yet. I'm not sure what timezone you're in, but would you be interested in having a chat video or otherwise, on a platform that allows a bit quicker back and forth? I could use some help deciding what the next steps here are

**Comment by naorzr** [comment]
@TylorS sorry about delayed response, didn't receive a notification from github.
I'm Gmt + 2.
Voice chat can work great, I'm available on the fp-ts slack channel, as naor z.
feel free to pm me, and let's continue from there.
